[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'cohama/vim-smartinput-endwise'

[[plugins]]
repo = 'fholgado/minibufexpl.vim'

[[plugins]]
repo = 'QuickBuf'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'jwalton512/vim-blade'

# colorschem
[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'

# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'

# vim-go
[[plugins]]
repo = 'fatih/vim-go'
